# Jalankan database seeding (Hapus data lama -> Migrate -> Seed)
seed:
	@echo "Mengosongkan dan mengisi database..."
	go run cmd/seed/main.go

# Membantu cek status database (Opsional)
db-status:
	@echo "Mengecek koneksi database..."
	# tambahkan perintah cek db jika perlu